modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Spiders%20Produce%20Webs"
logoFile="icon.png"

[[mods]]
modId="spidersproducewebs"
version="3.5"
displayName="Spiders Produce Webs"
displayURL="https://serilum.com/mod/spiders-produce-webs"
authors="Rick South"
description='''Spiders and cave spiders can periodically produce a web when a player is close.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., Nahuel Fernandez, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.spidersproducewebs]]
    modId="collective"
    mandatory=true
    versionRange="[7.80,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.spidersproducewebs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.21.1]"
    ordering="NONE"
    side="BOTH"
